# TODO
# general settings
# name: 201_RCANx2_scratch_DIV2K_rand0
name: RCANx2_RealSR_RGB400_real
model_type: SRModel
kernel_pool: false
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: RealSR_RAW
    type: PairedImageDataset
    # Bic /home/yangyuqiang/datasets/RealSR/RealSR_Raw/RGB300_train/LR/x2sub
    # Real /home/yangyuqiang/datasets/RealSR/RealSR_Raw/RGB300_LR2_sub
    dataroot_gt: /home/yangyuqiang/datasets/RealSR/RealSR_Raw/RAW_BLC_ECC_0217/RGB400/train/HRsub
    dataroot_lq: /home/yangyuqiang/datasets/RealSR/RealSR_Raw/RAW_BLC_ECC_0217/RGB400/train/LR2sub
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 96
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: RealSR_RAW
    type: PairedImageDataset
    dataroot_gt: /home/yangyuqiang/datasets/RealSR/RealSR_Raw/RAW_BLC_ECC_0217/RGB400/test/HR
    dataroot_lq: /home/yangyuqiang/datasets/RealSR/RealSR_Raw/RAW_BLC_ECC_0217/RGB400/test/LR2
    io_backend:
      type: disk

# network structures
network_g:
  type: RCAN
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_group: 10
  num_block: 20
  squeeze_factor: 16
  upscale: 2
  res_scale: 1
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]
  groups: 1

# path
path:
  pretrain_network_g: ~ #/home/yangyuqiang/tmp/BasicSR/experiments/RCANx2_RealSR_RGB300_real/models/net_g_165000.pth
  strict_load_g: true
  resume_state: ~ #/home/yangyuqiang/tmp/BasicSR/experiments/RCANx2_RealSR_RGB300_real/training_states/165000.state

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true
  save_type: png  # tiff or png

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
